### ISSUE TITLE
Doesn't seem to work correctly on Windows

### ISSUE THREAD

**Issue by mcdan** [apache/openwhisk-devtools#119]
Process:
1. Install Docker for Windows, get it running
2. Install Ubuntu Linux subsystem
3. Update the makefile to work with new docker binary names:  https://github.com/mcdan/incubator-openwhisk-devtools/tree/mcdan/feature/windows-support
4. The invokers still can't communicate with Docker for Windows:
https://forums.docker.com/t/where-is-the-file-docker-sock/13061
https://github.com/docker/for-win/issues/453
https://github.com/moby/moby/commit/0906195fbbd6f379c163b80f23e4c5a60bcfc5f0

This is sort of a fundamental difference in how Windows and Linux works and you can't make Windows list on all adapters only localhost so we're sort of stuck.

**Comment by hendrul** [comment]
I have been trying to make it work on windows with no success, now I'm depressed and with low self-confidence. I would appreciate someone fix this soon :(

**Comment by trebmalydna** [comment]
@mcdan Any luck making this work?

**Comment by kamyker** [comment]
Got it working using kubernetes https://github.com/apache/openwhisk-deploy-kube/blob/master/docs/k8s-docker-for-windows.md

Had to also run:
```
kubectl create namespace tiller-world
```
before 
```
helm install owdev ./helm/openwhisk -n openwhisk -f mycluster.yaml
```

**Comment by rabbah** [comment]
Closing as stale.
