### ISSUE TITLE
Docker-Compose: Migrate to dockerize instead of curl

### ISSUE THREAD

**Issue by ghost** [apache/openwhisk-devtools#126]
in current makefile there is curl --silent with un-ended loop.

please migrate to https://github.com/jwilder/dockerize - it has function  `dockerize -wait <someurl>`

**Comment by allustin** [comment]
this is a loop wtihout timeout, for example

https://github.com/apache/incubator-openwhisk-devtools/blob/master/docker-compose/Makefile#L68

**Comment by jthomas** [comment]
Hello @allustin, thanks for raising this issue. 

Is this something you are familiar with? Would you like to have a go at submitting a PR with the change?
