### ISSUE TITLE
Problem in installing OpenWhisk in HA (high availability) mode

### ISSUE THREAD

**Issue by mayaraelaziz** [apache/openwhisk-devtools#137]
I am trying to install OpenWhisk in HA mode but changes doesn't have an effect. 

I have made the following changes 

1. edited this [command](https://github.com/apache/incubator-openwhisk-devtools/blob/926dca9ad6760c5c37df84c375c8f5aacbfb02ed/docker-compose/Makefile#L249-L254) to take as an argument `-e mode=HA` to be 	

```
docker run --rm -v ~/tmp/openwhisk/src:/openwhisk -w /openwhisk/ansible \
		--network="$${compose_network}" -t \
		--add-host="db:$${db_ip_address}" \
		ddragosd/ansible:2.4.0.0-debian8  \
		sh -c "ansible-playbook -e mode=HA setup.yml && ansible-playbook couchdb.yml --tags=ini && ansible-playbook initdb.yml wipe.yml \
			-e db_host=db -e openwhisk_home=/openwhisk -e db_prefix=$(OPEN_WHISK_DB_PREFIX)"
```

2. uncommented the following line in the [hosts](https://github.com/apache/incubator-openwhisk/blob/5e1571a61aa606eecfef7d7e44d46187d29e0026/ansible/environments/docker-machine/hosts.j2.ini#L11-L13) file but running `make quick-start` always overrides these changes before deployment.

**Comment by rabbah** [comment]
Closing as stale. This deployment wasn't intended for HA. If there's interest in this, happy to revisit or accept a PR.
