### ISSUE TITLE
CouchDB shows error of database not exist after make restart

### ISSUE THREAD

**Issue by xgenvn** [apache/openwhisk-devtools#177]
Hi,

Is it by design we have to re-init couchdb right after every restart?

I'm using PhotonOS VM for testing.
Everything is working fine unless I try using `make stop` or `make restart`.
The issue I found is related to CouchDB with the logs `database not exists`.

`make init-couchdb` solves the issue, but then I have to deploy my service again (using serverless).

**Comment by rabbah** [comment]
You would need to mount a persisted volume to preserve couchdb's state across restarts. By default this is not the default mode. Other deployment modes might be more appropriate depending on what you want to do. For example the standalone openwhisk model allows for persisted couchdb.
