### ISSUE TITLE
Unable to create action -status code 500

### ISSUE THREAD

**Issue by 223311** [apache/openwhisk-devtools#198]
Hi,
i got the following error ,when i am trying create a action with size of 115 MB. At the same time if run another action with file size less than 5 mb , openwhisk is able to create that  #action. 

error: Unable to create action 'objrec': The connection failed, or timed out. (HTTP status code 500)

i tried to change "client_max_body_size"(location :incubator-openwhisk-devtools-master\docker-compose\apigateway\generated-conf.d\whisk-docker-compose.conf)  to 5000m but i am getting same error.Before i was change value  to 5000m ,i was getting 
error: Unable to create action 'objrec': The connection failed, or timed out. (HTTP status code 413)

Thanks,
Sankar

**Comment by rabbah** [comment]
The default limit is 48MB on actions - anything greater will fail.
Making this configurable requires some work upstream. Did you try using a docker action instead?

**Comment by 223311** [comment]
Thanks :)
