### ISSUE TITLE
apply wait-for-docker-compose-up.patch into Makefile, compilation errors

### ISSUE THREAD

**Issue by Bobyuan1015** [apache/openwhisk-devtools#204]
Starting openwhisk_db_1        ... done
Starting openwhisk_kafka_1     ... 
WARNING: The DOCKER_COMPOSE_HOST variable is not set. Defaulting to a blank string.
/bin/sh: 5: function: not found
/bin/sh: 7: Syntax error: ";" unexpected
Makefile:266: recipe for target 'wait-for-docker-compose-up' failed

**Comment by aBetterFun** [comment]
have you fixed this? I have the same issue here.
