### ISSUE TITLE
allow for existing local Kafka

### ISSUE THREAD

**Issue by lxghtless** [apache/openwhisk-devtools#228]
Feature Request:

Problem:
'Port 9092 is taken by PID:XXXX'

Caused By:
I run the [Confluent Platform](https://docs.confluent.io/current/quickstart/ce-quickstart.html#ce-quickstart) locally for daily development.

Workaround:
`confluent stop` or `confluent destroy`... then `make quick-start`

Feature Request:
Allow use of an existing local Kafka setup, as this disrupts local development workflows for developers like myself that use Kafka in other projects on a daily basis.

**Comment by rabbah** [comment]
If there's interest in this, we're happy to accept a PR. The kubernetes and ansible deployment allow for external kafka.
