### ISSUE TITLE
Minio image tag not found in docker-compose.yaml

### ISSUE THREAD

**Issue by c5haw** [apache/openwhisk-devtools#273]
https://github.com/apache/incubator-openwhisk-devtools/blob/c3ce36d2086d06427e73df35a9370c55269c2ded/docker-compose/docker-compose.yml#L134

I am trying to run your `make start-docker-compose` script which executes docker-compose up on `docker-compose.yaml`. I am getting the following error:

```
.Pulling minio (minio/minio:RELEASE.2018-07-13T00-09-07Z)...
..ERROR: Get https://registry-1.docker.io/v2/minio/minio/manifests/RELEASE.2018-07-13T00-09-07Z: Get https://auth.docker.io/token?scope=repository%3Aminio%2Fminio%3Apull&service=registry.docker.io: EOF
```

I have looked on the builds for minio on Docker Hub and I can see that the tag referenced does not exist:
[Minio tags](https://hub.docker.com/r/minio/minio/builds?page=10)

I have had to manually patch this on my machine currently and point to the `edge` tag to fix, but I did this as a temporary solution to try and get it working for now. I believe this bodes further consideration first.

This is one of a number of issues that seem to have cropped up, that I am finding, since a recent update to the repository, such as having changed how you tag your images, which has broken older versions of the docker-compose process using the `Makefile`.

On a separate note, will these builds eventually be versioned or will they continue to be tagged in a backwards incompatible way? I am trying to create a build process that is deterministic and currently I am unable to achieve this.

Thanks!

**Comment by rabbah** [comment]
@c5haw thank you for the report and feedback. 

> On a separate note, will these builds eventually be versioned or will they continue to be tagged in a backwards incompatible way? I am trying to create a build process that is deterministic and currently I am unable to achieve this.

Yes, we need to do that as there are many developers depending on this now and we have released all the dependent components (modulo one more update to the main repo).
