### ISSUE TITLE
OPENWHISK MAKE QUICK START FALLS

### ISSUE THREAD

**Issue by pepiparaskev30** [apache/openwhisk-devtools#274]
Hello, please help me with the installation of Openwhisk:
I have the below problem:
I installed docker as it is referred in the instructions, after that i installed docker compose and java 8. 
After that i made:
git clone https://github.com/apache/incubator-openwhisk-devtools.git
cd incubator-openwhisk-devtools/docker-compose
make quick-start

BUT ! THE INSTALLATION OF MAKE QUICK-START FALLS AND THE PROBLEM IS THE BELOW:
Installing apimgmt package
error: Package update failed: Put https://83.212.97.203/api/v1/namespaces/whisk.system/packages/apimgmt?overwrite=true: dial tcp 83.212.97.203:443: getsockopt: connection refused
Makefile:352: recipe for target 'init-api-management' failed
make: *** [init-api-management] Error 3
 PLEASE HELP!!

**Comment by HassanMojab** [comment]
I had this issue caused by my docker DNS configuration. I fixed it by removing my custom docker daemon config file at `/etc/docker/daemon.json` and restarted my docker daemon.

**Comment by lyuxiaosu** [comment]
@pepiparaskev30 I encountered the same problem, did you resovle it?

**Comment by pepiparaskev30** [comment]
Try this:
docker pull openwhisk/action-nodejs-v10:nightly    
And then again:

Make quick start
