### ISSUE TITLE
There is no python2 image with nightly tag

### ISSUE THREAD

**Issue by style95** [apache/openwhisk-devtools#278]
Currently compose setup OpenWhisk with python2 runtime, but there is no docker image with `nightly` tag for python2.
So users are unable to invoke python2 action.

```
2019-08-07T08:31:09.972Z] [ERROR] [#tid_4AmAKSd56LiUSH63j2NI1GULHlSjqaT1] [DockerClientWithFileAccess] info: command was unsuccessful, code: 125 (unsuccessful), stdout: , stderr: Unable to find image 'openwhisk/python2action:nightly' loc
/usr/bin/docker: Error response from daemon: manifest for openwhisk/python2action:nightly not found. 
```

**Comment by style95** [comment]
We need to drop python2 for compose based setup or add "nightly" image for python2.

**Comment by dgrove-oss** [comment]
I believe the decision was made to stop building the python2 image a while back because python2 is end-of-life January 1, 2020.

**Comment by rabbah** [comment]
we should retag the "latest" image to "nightly" though - there's still a lot of p2 code out there.

**Comment by dgrove-oss** [comment]
Why not use 1.13.0-incubating as the tag?  it's the same bits as 'latest'.   I could add a 'nightly' as well I suppose, don't really care.

**Comment by dgrove-oss** [comment]
Nightly tag added as alias to 1.13.0-incubating/latest.

**Comment by style95** [comment]
I confirmed we can invoke python2 action with docker-compose based setup.

Thanks @dgrove-oss
