### ISSUE TITLE
[docker-compose] Create jenkins job that runs when a new a new commits lands in core openwhisk

### ISSUE THREAD

**Issue by csantanapr** [apache/openwhisk-devtools#28]
This allows to notify us if there is a change in core openwhisk docker images that brakes docker-compose flow.
The jenkins notifications are currently going to Slack channel #dev.
We could also look into opening an issue on this REPO when there is a failure.

**Comment by csantanapr** [comment]
depends on #25

**Comment by duynguyen** [comment]
@csantanapr which jenkins image do you use to run the job? I want to run it to test my script.

**Comment by chetanmeh** [comment]
@csantanapr Given current travis cron to build every 24 hrs I think we can close this issue?
