### ISSUE TITLE
Localization problem in Makefile

### ISSUE THREAD

**Issue by anbo-de** [apache/openwhisk-devtools#282]
The installation causes problems due to the IP address. It is not found due to a localization problem in the Makefile. In https://github.com/apache/openwhisk-devtools/blob/master/docker-compose/Makefile#L5 an English representation of the output is expected. However, in a localized shell (e.g., German) the output looks different (e.g., in a German shell the output is "inet Adresse:" instead of "inet addr:"). Therefore, the command is not executed properly.

**Comment by anbo-de** [comment]
corresponding pull request: https://github.com/apache/openwhisk-devtools/pull/283

**Comment by dgrove-oss** [comment]
PR was merged; closing issue
