### ISSUE TITLE
make quick-start fails on ubuntu 18.04 lts 

### ISSUE THREAD

**Issue by navdeepkk** [apache/openwhisk-devtools#303]
Did exactly everything said in the tutorial but end up with this error.
ok: invoked /_/hello, but the request has not yet finished.

**Comment by colo76** [comment]
> Did exactly everything said in the tutorial but end up with this error.
> ok: invoked /_/hello, but the request has not yet finished.

are you aware of this? --> https://github.com/apache/openwhisk-devtools/issues/276
It worked for me.
