### ISSUE TITLE
Docker-compose scale-up for multiple invokers/controllers does not work!

### ISSUE THREAD

**Issue by ali-raza-tariq** [apache/openwhisk-devtools#305]
I was testing with scaling-up the concurrency limit of docker-compose deployment. I found the variables (`CONTROLLER_INSTANCES` & `INVOKER_INSTANCES`) in `docker-whisk-controller.env` which have a default value of 1. While testing, I couldn't help but notice that changing the values of above mentioned variables has no impact on the initialized containers. Looking into the `Makefile`, it simply starts the containers using `docker-compose.yaml` file which doesn't take into account the above mentioned variable. 

Is this behavior intentional? or is it a bug in the implementation?

**Comment by ali-raza-tariq** [comment]
@ddragosd could you confirm if this is indeed a bug, because I would like to work on this!

**Comment by rabbah** [comment]
looks like a bug to me.

**Comment by rabbah** [comment]
Closing as stale. The kubernetes and ansible deployments support scale out. If there's interest in supporting those with compose, we're happy to accept a PR.
