### ISSUE TITLE
Fail in make quick-start

### ISSUE THREAD

**Issue by paulrm** [apache/openwhisk-devtools#318]
Executing  make quick-start in ubuntu 18.04.4, enter in loop setting up the couchdb

```
Pulling db (apache/couchdb:2.3)...
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
/bin/sh: 28: let: not found
```

**Comment by kuwii** [comment]
Try adding this at the beginning of ```docker-compose/Makefile```, which works for me:

```
SHELL:=/bin/bash
```
