### ISSUE TITLE
Please keep Makefile upto date

### ISSUE THREAD

**Issue by pankaj-dahiya** [apache/openwhisk-devtools#320]
There is major change in package-alarms, 2 months ago, but nothing changed in Makefile.

https://github.com/apache/openwhisk-package-alarms/commit/e248a564f4f163d0cb4cca0afd3c56c63a4ed71b

This shows that while calling install-package-alarms there are significant changes in parameters but in Makefile they are still not changed.

In Makefile, we are calling installCatalogUsingWskDeploy.sh whereas in it must be installCatalog.sh.

**Comment by dyllandry** [comment]
Hopefully bumping this will get it more attention. That commit adds a few required vars that I do not know where to get.

**Comment by style95** [comment]
@Keonhee
Could you take a look at this?

**Comment by KeonHee** [comment]
Ok I will try to handle this issue.
