### ISSUE TITLE
exec user process caused "exec format error" on raspberry 4B 8GB

### ISSUE THREAD

**Issue by mcmaur** [apache/openwhisk-devtools#323]
Hi,
I followed this steps on my Raspberry Pi 4 Model B 8GB ram:
```
git clone https://github.com/apache/incubator-openwhisk-devtools.git 
cd incubator-openwhisk-devtools/docker-compose
make quick-start
```
During the procedure it is stuck after "pinging minio..." and it continues on printing dot. I analyzed the makefile and found out and it makes a call to the followind url
`curl --silent http://$(DOCKER_HOST_IP):9001/ `

I then found out that the container "minio" was not running. I tried to run it manually but it stops with an error:
`standard_init_linux.go:211: exec user process caused "exec format error"`

Is this procedure compatible with armv8?

**Comment by style95** [comment]
I haven't tried this but how about trying with the standalone openwhisk instead?
I believe you can get it more easily running.
https://github.com/apache/openwhisk/tree/master/core/standalone

**Comment by mcmaur** [comment]
I followed this: [](https://medium.com/openwhisk/apache-openwhisk-meets-raspberry-pi-e346e555b56a)
it works

**Comment by style95** [comment]
Great!

**Comment by christiansicari** [comment]
> I followed this: [medium.com/openwhisk/apache-openwhisk-meets-raspberry-pi](https://medium.com/openwhisk/apache-openwhisk-meets-raspberry-pi-e346e555b56a) it works

unfortunately does not work on Armv8 Raspberry.
I changed the Minio Tag using this: RELEASE.2020-11-25T22-36-25Z-arm64
But I got this
```
host ip address: 155.98.20.227
checking required ports ... 
 ... OK
  ... preparing api-gateway configuration
pinging minio...
.Traceback (most recent call last):
  File "/usr/local/bin/docker-compose", line 5, in <module>
    from compose.cli.main import main
  File "/usr/local/lib/python3.9/dist-packages/compose/cli/main.py", line 29, in <module>
    from ..metrics.decorator import metrics
  File "/usr/local/lib/python3.9/dist-packages/compose/metrics/decorator.py", line 3, in <module>
    from compose.metrics.client import MetricsCommand
  File "/usr/local/lib/python3.9/dist-packages/compose/metrics/client.py", line 5, in <module>
    from docker import ContextAPI
ImportError: cannot import name 'ContextAPI' from 'docker' (/usr/l
```
Honestly I think there is no interest on ARM deployment without Kubernetes
