### ISSUE TITLE
The function can be created, but cannot run, prompt  "The server is currently unavailable (because it is overloaded or down for maintenance)."

### ISSUE THREAD

**Issue by crazyzcc619** [apache/openwhisk-devtools#326]
The function can be created, but cannot run, prompt
 "The server is currently unavailable (because it is overloaded or down for maintenance)."

**Comment by rabbah** [comment]
Check your controller logs - this could mean that the database isn't reachable or the invokers are offline.
Unless you need a docker compose deployment, I suggest using the standalone openwhisk mode https://github.com/apache/openwhisk/blob/master/core/standalone/README.md
