### ISSUE TITLE
waiting for the Whisk invoker to come up ... seems to be going on forever

### ISSUE THREAD

**Issue by LaithaSankar** [apache/openwhisk-devtools#346]

**Comment by xx01cyx** [comment]
I encounter the problem as well. Any solution to this? 👀

**Comment by Areej-Fatima** [comment]
I have the same problem, any possible fixes?

**Comment by Areej-Fatima** [comment]
In Makefile, on line 101, remove `--head` flag.
Before: `	until $$(curl -s --output /dev/null --silent --head --fail http://$(DOCKER_HOST_IP):8085/ping); do printf '.'; sleep 5; done`
After:`	until $$(curl -s --output /dev/null --silent --fail http://$(DOCKER_HOST_IP):8085/ping); do printf '.'; sleep 5; done
`

**Comment by Genius514D4A** [comment]
> 我有同样的问题，有什么可能的解决方法吗？

你解决了吗

**Comment by rabbah** [comment]
You should check the invoker logs for clues. There's nothing here in this issue to help.
